### ISSUE TITLE
What is the proper work flow to get other games supported?

### ISSUE THREAD

**Issue by asesidaa** [ProjectAsakura/OpenBanapass#3]
Hi, I am trying to get this work for Taiko nijiiro. Currently the game just calls `BngRwInit` and `BngRwAttach` and fails to recognize the emulated card reader. I wonder what is the proper work flow if I want to get Taiko supported?

One thing I noticed is that the version string is `Ver 1.6.1` instead of `Ver 1.6.0`, so probably something has changed

**Comment by asesidaa** [comment]
Seems to be working

**Comment by snightshade** [comment]
ooooh, taiko huh?

**Comment by asesidaa** [comment]
It seems that the callback is the key, and they might be different for each game

**Comment by snightshade** [comment]
The workflow for other games support is to bring it up to me (rin#3487 on Discord) btw lmao
